package Gi;

import android.util.SparseArray;
import androidx.databinding.library.baseAdapters.BR;
import com.samsung.android.honeyboard.predictionengine.core.xt9.datatype.Xt9Datatype;
import com.samsung.android.sdk.routines.v3.data.parameter.representation.ParameterRepresentation;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

/* JADX INFO: loaded from: classes3.dex */
public abstract class c {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final HashMap f3080a;

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final HashMap f3081b;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    public static final ArrayList f3082c;

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final SparseArray f3083d;

    static {
        HashSet hashSet = new HashSet();
        HashMap map = new HashMap();
        f3080a = map;
        HashMap map2 = new HashMap();
        f3081b = map2;
        ArrayList arrayList = new ArrayList();
        f3082c = arrayList;
        SparseArray sparseArray = new SparseArray();
        f3083d = sparseArray;
        hashSet.add(65281);
        hashSet.add(8221);
        hashSet.add(65283);
        hashSet.add(65284);
        hashSet.add(65285);
        hashSet.add(65286);
        hashSet.add(8217);
        hashSet.add(65288);
        hashSet.add(65289);
        hashSet.add(65309);
        hashSet.add(65374);
        hashSet.add(65372);
        hashSet.add(65344);
        hashSet.add(65371);
        hashSet.add(65291);
        hashSet.add(65290);
        hashSet.add(65373);
        hashSet.add(65308);
        hashSet.add(65310);
        hashSet.add(Integer.valueOf(Xt9Datatype.ET9CPCANGJIEWILDCARD));
        hashSet.add(65343);
        hashSet.add(65342);
        hashSet.add(65509);
        hashSet.add(65312);
        hashSet.add(12300);
        hashSet.add(65307);
        hashSet.add(65306);
        hashSet.add(12301);
        hashSet.add(12289);
        hashSet.add(12290);
        hashSet.add(12539);
        hashSet.add(92);
        map.put("あ", "ぁ");
        map.put("い", "ぃ");
        map.put("う", "ぅ");
        map.put("え", "ぇ");
        map.put("お", "ぉ");
        map.put("ぁ", "あ");
        map.put("ぃ", "い");
        map.put("ぅ", "ゔ");
        map.put("ぇ", "え");
        map.put("ぉ", "お");
        map.put("か", "が");
        map.put("き", "ぎ");
        map.put("く", "ぐ");
        map.put("け", "げ");
        map.put("こ", "ご");
        map.put("が", "か");
        map.put("ぎ", "き");
        map.put("ぐ", "く");
        map.put("げ", "け");
        map.put("ご", "こ");
        map.put("さ", "ざ");
        map.put("し", "じ");
        map.put("す", "ず");
        map.put("せ", "ぜ");
        map.put("そ", "ぞ");
        map.put("ざ", "さ");
        map.put("じ", "し");
        map.put("ず", "す");
        map.put("ぜ", "せ");
        map.put("ぞ", "そ");
        map.put("た", "だ");
        map.put("ち", "ぢ");
        map.put("つ", "っ");
        map.put("て", "で");
        map.put("と", "ど");
        map.put("だ", "た");
        map.put("ぢ", "ち");
        map.put("っ", "づ");
        map.put("で", "て");
        map.put("ど", "と");
        map.put("づ", "つ");
        map.put("ゔ", "う");
        map.put("は", "ば");
        map.put("ひ", "び");
        map.put("ふ", "ぶ");
        map.put("へ", "べ");
        map.put("ほ", "ぼ");
        map.put("ば", "ぱ");
        map.put("び", "ぴ");
        map.put("ぶ", "ぷ");
        map.put("べ", "ぺ");
        map.put("ぼ", "ぽ");
        map.put("ぱ", "は");
        map.put("ぴ", "ひ");
        map.put("ぷ", "ふ");
        map.put("ぺ", "へ");
        map.put("ぽ", "ほ");
        map.put("や", "ゃ");
        map.put("ゆ", "ゅ");
        map.put("よ", "ょ");
        map.put("ゃ", "や");
        map.put("ゅ", "ゆ");
        map.put("ょ", "よ");
        map.put("わ", "ゎ");
        map.put("ゎ", "わ");
        map.put("゛", "゜");
        map.put("゜", "゛");
        map2.put("la", "ぁ");
        map2.put("xa", "ぁ");
        map2.put("a", "あ");
        map2.put("li", "ぃ");
        map2.put("lyi", "ぃ");
        map2.put("xi", "ぃ");
        map2.put("xyi", "ぃ");
        map2.put("i", "い");
        map2.put("yi", "い");
        map2.put("ye", "いぇ");
        map2.put("lu", "ぅ");
        map2.put("xu", "ぅ");
        map2.put("u", "う");
        map2.put("whu", "う");
        map2.put("wu", "う");
        map2.put("wha", "うぁ");
        map2.put("whi", "うぃ");
        map2.put("wi", "うぃ");
        map2.put("we", "うぇ");
        map2.put("whe", "うぇ");
        map2.put("who", "うぉ");
        map2.put("le", "ぇ");
        map2.put("lye", "ぇ");
        map2.put("xe", "ぇ");
        map2.put("xye", "ぇ");
        map2.put("e", "え");
        map2.put("lo", "ぉ");
        map2.put("xo", "ぉ");
        map2.put("o", "お");
        map2.put("ca", "か");
        map2.put("ka", "か");
        map2.put("ga", "が");
        map2.put("ki", "き");
        map2.put("kyi", "きぃ");
        map2.put("kye", "きぇ");
        map2.put("kya", "きゃ");
        map2.put("kyu", "きゅ");
        map2.put("kyo", "きょ");
        map2.put("gi", "ぎ");
        map2.put("gyi", "ぎぃ");
        map2.put("gye", "ぎぇ");
        map2.put("gya", "ぎゃ");
        map2.put("gyu", "ぎゅ");
        map2.put("gyo", "ぎょ");
        map2.put("cu", "く");
        map2.put("ku", "く");
        map2.put("qu", "く");
        map2.put("kwa", "くぁ");
        map2.put("qa", "くぁ");
        map2.put("qwa", "くぁ");
        map2.put("qi", "くぃ");
        map2.put("qwi", "くぃ");
        map2.put("qyi", "くぃ");
        map2.put("qwu", "くぅ");
        map2.put("qe", "くぇ");
        map2.put("qwe", "くぇ");
        map2.put("qye", "くぇ");
        map2.put("qo", "くぉ");
        map2.put("qwo", "くぉ");
        map2.put("qya", "くゃ");
        map2.put("qyu", "くゅ");
        map2.put("qyo", "くょ");
        map2.put("gu", "ぐ");
        map2.put("gwa", "ぐぁ");
        map2.put("gwi", "ぐぃ");
        map2.put("gwu", "ぐぅ");
        map2.put("gwe", "ぐぇ");
        map2.put("gwo", "ぐぉ");
        map2.put("ke", "け");
        map2.put("ge", "げ");
        map2.put("co", "こ");
        map2.put("ko", "こ");
        map2.put("go", "ご");
        map2.put("sa", "さ");
        map2.put("za", "ざ");
        map2.put("ci", "し");
        map2.put("shi", "し");
        map2.put("si", "し");
        map2.put("syi", "しぃ");
        map2.put("she", "しぇ");
        map2.put("sye", "しぇ");
        map2.put("sha", "しゃ");
        map2.put("sya", "しゃ");
        map2.put("shu", "しゅ");
        map2.put("syu", "しゅ");
        map2.put("sho", "しょ");
        map2.put("syo", "しょ");
        map2.put("ji", "じ");
        map2.put("zi", "じ");
        map2.put("jyi", "じぃ");
        map2.put("zyi", "じぃ");
        map2.put("je", "じぇ");
        map2.put("jye", "じぇ");
        map2.put("zye", "じぇ");
        map2.put("ja", "じゃ");
        map2.put("jya", "じゃ");
        map2.put("zya", "じゃ");
        map2.put("ju", "じゅ");
        map2.put("jyu", "じゅ");
        map2.put("zyu", "じゅ");
        map2.put("jo", "じょ");
        map2.put("jyo", "じょ");
        map2.put("zyo", "じょ");
        map2.put("su", "す");
        map2.put("swa", "すぁ");
        map2.put("swi", "すぃ");
        map2.put("swu", "すぅ");
        map2.put("swe", "すぇ");
        map2.put("swo", "すぉ");
        map2.put("zu", "ず");
        map2.put("ce", "せ");
        map2.put("se", "せ");
        map2.put("ze", "ぜ");
        map2.put("so", "そ");
        map2.put("zo", "ぞ");
        map2.put("ta", "た");
        map2.put("da", "だ");
        map2.put("chi", "ち");
        map2.put("ti", "ち");
        map2.put("cyi", "ちぃ");
        map2.put("tyi", "ちぃ");
        map2.put("che", "ちぇ");
        map2.put("cye", "ちぇ");
        map2.put("tye", "ちぇ");
        map2.put("cha", "ちゃ");
        map2.put("cya", "ちゃ");
        map2.put("tya", "ちゃ");
        map2.put("chu", "ちゅ");
        map2.put("cyu", "ちゅ");
        map2.put("tyu", "ちゅ");
        map2.put("cho", "ちょ");
        map2.put("cyo", "ちょ");
        map2.put("tyo", "ちょ");
        map2.put("di", "ぢ");
        map2.put("dyi", "ぢぃ");
        map2.put("dye", "ぢぇ");
        map2.put("dya", "ぢゃ");
        map2.put("dyu", "ぢゅ");
        map2.put("dyo", "ぢょ");
        map2.put("ltsu", "っ");
        map2.put("ltu", "っ");
        map2.put("xtu", "っ");
        map2.put("xtsu", "っ");
        map2.put("tsu", "つ");
        map2.put("tu", "つ");
        map2.put("tsa", "つぁ");
        map2.put("tsi", "つぃ");
        map2.put("tse", "つぇ");
        map2.put("tso", "つぉ");
        map2.put("du", "づ");
        map2.put("te", "て");
        map2.put("thi", "てぃ");
        map2.put("the", "てぇ");
        map2.put("tha", "てゃ");
        map2.put("thu", "てゅ");
        map2.put("tho", "てょ");
        map2.put("de", "で");
        map2.put("dhi", "でぃ");
        map2.put("dhe", "でぇ");
        map2.put("dha", "でゃ");
        map2.put("dhu", "でゅ");
        map2.put("dho", "でょ");
        map2.put("to", "と");
        map2.put("twa", "とぁ");
        map2.put("twi", "とぃ");
        map2.put("twu", "とぅ");
        map2.put("twe", "とぇ");
        map2.put("two", "とぉ");
        map2.put("do", "ど");
        map2.put("dwa", "どぁ");
        map2.put("dwi", "どぃ");
        map2.put("dwu", "どぅ");
        map2.put("dwe", "どぇ");
        map2.put("dwo", "どぉ");
        map2.put("na", "な");
        map2.put("ni", "に");
        map2.put("nyi", "にぃ");
        map2.put("nye", "にぇ");
        map2.put("nya", "にゃ");
        map2.put("nyu", "にゅ");
        map2.put("nyo", "にょ");
        map2.put("nu", "ぬ");
        map2.put("ne", "ね");
        map2.put("no", "の");
        map2.put("ha", "は");
        map2.put("ba", "ば");
        map2.put("pa", "ぱ");
        map2.put("hi", "ひ");
        map2.put("hyi", "ひぃ");
        map2.put("hye", "ひぇ");
        map2.put("hya", "ひゃ");
        map2.put("hyu", "ひゅ");
        map2.put("hyo", "ひょ");
        map2.put("bi", "び");
        map2.put("byi", "びぃ");
        map2.put("bye", "びぇ");
        map2.put("bya", "びゃ");
        map2.put("byu", "びゅ");
        map2.put("byo", "びょ");
        map2.put("pi", "ぴ");
        map2.put("pyi", "ぴぃ");
        map2.put("pye", "ぴぇ");
        map2.put("pya", "ぴゃ");
        map2.put("pyu", "ぴゅ");
        map2.put("pyo", "ぴょ");
        map2.put("fu", "ふ");
        map2.put("hu", "ふ");
        map2.put("fa", "ふぁ");
        map2.put("fwa", "ふぁ");
        map2.put("fi", "ふぃ");
        map2.put("fwi", "ふぃ");
        map2.put("fyi", "ふぃ");
        map2.put("fwu", "ふぅ");
        map2.put("fe", "ふぇ");
        map2.put("fwe", "ふぇ");
        map2.put("fye", "ふぇ");
        map2.put("fo", "ふぉ");
        map2.put("fwo", "ふぉ");
        map2.put("fya", "ふゃ");
        map2.put("fyu", "ふゅ");
        map2.put("fyo", "ふょ");
        map2.put("bu", "ぶ");
        map2.put("pu", "ぷ");
        map2.put("he", "へ");
        map2.put("be", "べ");
        map2.put("pe", "ぺ");
        map2.put("ho", "ほ");
        map2.put("bo", "ぼ");
        map2.put("po", "ぽ");
        map2.put("ma", "ま");
        map2.put("mi", "み");
        map2.put("myi", "みぃ");
        map2.put("mye", "みぇ");
        map2.put("mya", "みゃ");
        map2.put("myu", "みゅ");
        map2.put("myo", "みょ");
        map2.put("mu", "む");
        map2.put("me", "め");
        map2.put("mo", "も");
        map2.put("lya", "ゃ");
        map2.put("xya", "ゃ");
        map2.put("ya", "や");
        map2.put("lyu", "ゅ");
        map2.put("xyu", "ゅ");
        map2.put("yu", "ゆ");
        map2.put("lyo", "ょ");
        map2.put("xyo", "ょ");
        map2.put("yo", "よ");
        map2.put("ra", "ら");
        map2.put("ri", "り");
        map2.put("ryi", "りぃ");
        map2.put("rye", "りぇ");
        map2.put("rya", "りゃ");
        map2.put("ryu", "りゅ");
        map2.put("ryo", "りょ");
        map2.put("ru", "る");
        map2.put("re", "れ");
        map2.put("ro", "ろ");
        map2.put("lwa", "ゎ");
        map2.put("xwa", "ゎ");
        map2.put("wa", "わ");
        map2.put("wo", "を");
        map2.put("nn", "ん");
        map2.put("xn", "ん");
        map2.put("vu", "ゔ");
        map2.put("va", "ゔぁ");
        map2.put("vi", "ゔぃ");
        map2.put("vyi", "ゔぃ");
        map2.put("ve", "ゔぇ");
        map2.put("vye", "ゔぇ");
        map2.put("vo", "ゔぉ");
        map2.put("vya", "ゔゃ");
        map2.put("vyu", "ゔゅ");
        map2.put("vyo", "ゔょ");
        map2.put("bb", "っb");
        map2.put("cc", "っc");
        map2.put("dd", "っd");
        map2.put("ff", "っf");
        map2.put("gg", "っg");
        map2.put("hh", "っh");
        map2.put("jj", "っj");
        map2.put("kk", "っk");
        map2.put("ll", "っl");
        map2.put("mm", "っm");
        map2.put("pp", "っp");
        map2.put("qq", "っq");
        map2.put("rr", "っr");
        map2.put("ss", "っs");
        map2.put("tt", "っt");
        map2.put("vv", "っv");
        map2.put("ww", "っw");
        map2.put("xx", "っx");
        map2.put("yy", "っy");
        map2.put("zz", "っz");
        map2.put("nb", "んb");
        map2.put("nc", "んc");
        map2.put("nd", "んd");
        map2.put("nf", "んf");
        map2.put("ng", "んg");
        map2.put("nh", "んh");
        map2.put("nj", "んj");
        map2.put("nk", "んk");
        map2.put("nm", "んm");
        map2.put("np", "んp");
        map2.put("nq", "んq");
        map2.put("nr", "んr");
        map2.put("ns", "んs");
        map2.put("nt", "んt");
        map2.put("nv", "んv");
        map2.put("nw", "んw");
        map2.put("nx", "んx");
        map2.put("nz", "んz");
        map2.put("nl", "んl");
        map2.put("-", "ー");
        map2.put(".", "。");
        map2.put(",", "、");
        map2.put("?", "？");
        map2.put("/", "・");
        map2.put("@", "＠");
        map2.put("#", "＃");
        map2.put("%", "％");
        map2.put("&", "＆");
        map2.put("*", "＊");
        map2.put("+", "＋");
        map2.put("=", "＝");
        map2.put("(", "（");
        map2.put(")", "）");
        map2.put("~", "～");
        map2.put("\"", "”");
        map2.put("'", "’");
        map2.put(":", "：");
        map2.put(";", "；");
        map2.put("!", "！");
        map2.put("^", "＾");
        map2.put("¥", "￥");
        map2.put("$", "＄");
        map2.put("[", "「");
        map2.put("]", "」");
        map2.put("_", "＿");
        map2.put("{", "｛");
        map2.put(ParameterRepresentation.LINKED_PATTERN_SUBSEQUENT, "｝");
        map2.put("`", "｀");
        map2.put("<", "＜");
        map2.put(">", "＞");
        map2.put("\\", "＼");
        map2.put("|", "｜");
        A2.a.t(arrayList, "()", "[]", "{}", "«»");
        A2.a.t(arrayList, "“”", "‘’", "””", "’’");
        A2.a.t(arrayList, "„“", "‚‘", "„”", "‛’");
        A2.a.t(arrayList, "‹›", "❨❩", "❪❫", "❬❭");
        A2.a.t(arrayList, "❮❯", "❰❱", "❲❳", "❴❵");
        A2.a.t(arrayList, "⦅⦆", "〈〉", "《》", "「」");
        A2.a.t(arrayList, "『』", "【】", "〔〕", "〖〗");
        A2.a.t(arrayList, "〘〙", "〝〞", "〚〛", "﴾﴿");
        A2.a.t(arrayList, "︗︘", "︵︶", "︷︸", "︹︺");
        A2.a.t(arrayList, "︻︼", "︽︾", "︿﹀", "﹁﹂");
        A2.a.t(arrayList, "﹃﹄", "﹙﹚", "﹛﹜", "﹝﹞");
        A2.a.t(arrayList, "（）", "［］", "｛｝", "｢｣");
        arrayList.add("<>");
        sparseArray.put(65281, 33);
        A2.a.o(35, sparseArray, 65283, 36, 65284);
        A2.a.o(37, sparseArray, 65285, 38, 65286);
        A2.a.o(40, sparseArray, 65288, 41, 65289);
        A2.a.o(42, sparseArray, 65290, 43, 65291);
        A2.a.o(44, sparseArray, 65292, 58, 65306);
        A2.a.o(59, sparseArray, 65307, 60, 65308);
        A2.a.o(61, sparseArray, 65309, 62, 65310);
        A2.a.o(63, sparseArray, Xt9Datatype.ET9CPCANGJIEWILDCARD, 64, 65312);
        A2.a.o(92, sparseArray, 65340, 94, 65342);
        A2.a.o(95, sparseArray, 65343, 96, 65344);
        A2.a.o(123, sparseArray, 65371, 124, 65372);
        A2.a.o(125, sparseArray, 65373, BR.revisionButtonShown, 65509);
        A2.a.o(39, sparseArray, 8217, 34, 8221);
        A2.a.o(126, sparseArray, 12316, 44, 12289);
        A2.a.o(46, sparseArray, 12290, 91, 12300);
        A2.a.o(93, sparseArray, 12301, 47, 12539);
        sparseArray.put(12540, 45);
    }
}
