package com.google.android.setupcompat.partnerconfig;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'CONFIG_STATUS_BAR_BACKGROUND' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:399)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:364)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:349)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:315)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:288)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: loaded from: classes2.dex */
public final class PartnerConfig {
    private static final /* synthetic */ PartnerConfig[] $VALUES;
    public static final PartnerConfig CONFIG_ACCOUNT_AVATAR_MARGIN_END;
    public static final PartnerConfig CONFIG_ACCOUNT_AVATAR_SIZE;
    public static final PartnerConfig CONFIG_ACCOUNT_CONTAINER_MARGIN_BOTTOM;
    public static final PartnerConfig CONFIG_ACCOUNT_CONTAINER_MARGIN_TOP;
    public static final PartnerConfig CONFIG_ACCOUNT_NAME_FONT_FAMILY;
    public static final PartnerConfig CONFIG_ACCOUNT_NAME_TEXT_SIZE;
    public static final PartnerConfig CONFIG_ASSISTIVE_OPTIONS_ACTIVITY_NAME;
    public static final PartnerConfig CONFIG_ASSISTIVE_OPTIONS_PACKAGE_NAME;
    public static final PartnerConfig CONFIG_CARD_VIEW_INTRINSIC_HEIGHT;
    public static final PartnerConfig CONFIG_CARD_VIEW_INTRINSIC_WIDTH;
    public static final PartnerConfig CONFIG_CARD_VIEW_SELECTED_RADIUS;
    public static final PartnerConfig CONFIG_CONTENT_FONT_FAMILY;
    public static final PartnerConfig CONFIG_CONTENT_INFO_FONT_FAMILY;
    public static final PartnerConfig CONFIG_CONTENT_INFO_ICON_MARGIN_END;
    public static final PartnerConfig CONFIG_CONTENT_INFO_ICON_SIZE;
    public static final PartnerConfig CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA;
    public static final PartnerConfig CONFIG_CONTENT_INFO_PADDING_BOTTOM;
    public static final PartnerConfig CONFIG_CONTENT_INFO_PADDING_TOP;
    public static final PartnerConfig CONFIG_CONTENT_INFO_TEXT_SIZE;
    public static final PartnerConfig CONFIG_CONTENT_LAYOUT_GRAVITY;
    public static final PartnerConfig CONFIG_CONTENT_LINK_TEXT_COLOR;
    public static final PartnerConfig CONFIG_CONTENT_PADDING_TOP;
    public static final PartnerConfig CONFIG_CONTENT_TEXT_COLOR;
    public static final PartnerConfig CONFIG_CONTENT_TEXT_SIZE;
    public static final PartnerConfig CONFIG_DESCRIPTION_FONT_FAMILY;
    public static final PartnerConfig CONFIG_DESCRIPTION_FONT_WEIGHT;
    public static final PartnerConfig CONFIG_DESCRIPTION_LINK_FONT_FAMILY;
    public static final PartnerConfig CONFIG_DESCRIPTION_LINK_TEXT_COLOR;
    public static final PartnerConfig CONFIG_DESCRIPTION_TEXT_COLOR;
    public static final PartnerConfig CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM;
    public static final PartnerConfig CONFIG_DESCRIPTION_TEXT_MARGIN_TOP;
    public static final PartnerConfig CONFIG_DESCRIPTION_TEXT_SIZE;
    public static final PartnerConfig CONFIG_FOOTER_BAR_BG_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_BAR_HIDE_WHEN_IME_SHOWN;
    public static final PartnerConfig CONFIG_FOOTER_BAR_MIN_HEIGHT;
    public static final PartnerConfig CONFIG_FOOTER_BAR_MORE_TO_SCROLL_BG_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_BAR_PADDING_END;
    public static final PartnerConfig CONFIG_FOOTER_BAR_PADDING_START;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ALIGNED_END;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_DISABLED_ALPHA;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_FONT_FAMILY;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_FONT_WEIGHT;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_CANCEL;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_CLEAR;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_DONE;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_NEXT;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_OPT_IN;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_SKIP;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_ICON_STOP;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_MIDDLE_SPACE;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_MIN_HEIGHT;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_PADDING_BOTTOM;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_PADDING_TOP;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_RADIUS;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_STACK_MIDDLE_SPACE;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_TEXT_SIZE;
    public static final PartnerConfig CONFIG_FOOTER_BUTTON_TEXT_STYLE;
    public static final PartnerConfig CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_PRIMARY_BUTTON_DISABLED_TEXT_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_PRIMARY_BUTTON_MARGIN_START;
    public static final PartnerConfig CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_SECONDARY_BUTTON_DISABLED_TEXT_COLOR;
    public static final PartnerConfig CONFIG_FOOTER_SECONDARY_BUTTON_MARGIN_START;
    public static final PartnerConfig CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR;
    public static final PartnerConfig CONFIG_HEADER_AREA_BACKGROUND_COLOR;
    public static final PartnerConfig CONFIG_HEADER_AUTO_SIZE_ENABLED;
    public static final PartnerConfig CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA;
    public static final PartnerConfig CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE;
    public static final PartnerConfig CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE;
    public static final PartnerConfig CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE;
    public static final PartnerConfig CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM;
    public static final PartnerConfig CONFIG_HEADER_FONT_FAMILY;
    public static final PartnerConfig CONFIG_HEADER_FONT_VARIATION_SETTINGS;
    public static final PartnerConfig CONFIG_HEADER_FONT_WEIGHT;
    public static final PartnerConfig CONFIG_HEADER_PROGRESS_BAR_COMMON_STYLE;
    public static final PartnerConfig CONFIG_HEADER_TEXT_COLOR;
    public static final PartnerConfig CONFIG_HEADER_TEXT_MARGIN_BOTTOM;
    public static final PartnerConfig CONFIG_HEADER_TEXT_MARGIN_TOP;
    public static final PartnerConfig CONFIG_HEADER_TEXT_SIZE;
    public static final PartnerConfig CONFIG_ICON_COLOR;
    public static final PartnerConfig CONFIG_ICON_MARGIN_TOP;
    public static final PartnerConfig CONFIG_ICON_SIZE;
    public static final PartnerConfig CONFIG_ILLUSTRATION_MAX_HEIGHT;
    public static final PartnerConfig CONFIG_ILLUSTRATION_MAX_WIDTH;
    public static final PartnerConfig CONFIG_ITEMS_BACKGROUND_COLOR;
    public static final PartnerConfig CONFIG_ITEMS_DIVIDER_SHOWN;
    public static final PartnerConfig CONFIG_ITEMS_GROUP_CORNER_RADIUS;
    public static final PartnerConfig CONFIG_ITEMS_MIN_HEIGHT;
    public static final PartnerConfig CONFIG_ITEMS_PADDING_BOTTOM;
    public static final PartnerConfig CONFIG_ITEMS_PADDING_TOP;
    public static final PartnerConfig CONFIG_ITEMS_SUMMARY_FONT_FAMILY;
    public static final PartnerConfig CONFIG_ITEMS_SUMMARY_MARGIN_TOP;
    public static final PartnerConfig CONFIG_ITEMS_SUMMARY_TEXT_SIZE;
    public static final PartnerConfig CONFIG_ITEMS_TITLE_FONT_FAMILY;
    public static final PartnerConfig CONFIG_ITEMS_TITLE_FONT_VARIATION_SETTINGS;
    public static final PartnerConfig CONFIG_ITEMS_TITLE_TEXT_SIZE;
    public static final PartnerConfig CONFIG_LAND_MIDDLE_HORIZONTAL_SPACING;
    public static final PartnerConfig CONFIG_LAYOUT_BACKGROUND_COLOR;
    public static final PartnerConfig CONFIG_LAYOUT_GRAVITY;
    public static final PartnerConfig CONFIG_LAYOUT_MARGIN_END;
    public static final PartnerConfig CONFIG_LAYOUT_MARGIN_START;
    public static final PartnerConfig CONFIG_LIGHT_NAVIGATION_BAR;
    public static final PartnerConfig CONFIG_LIGHT_STATUS_BAR;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_HEADER_HEIGHT;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_PADDING_BOTTOM;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_PADDING_END;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_PADDING_START;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_PADDING_TOP;
    public static final PartnerConfig CONFIG_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED;
    public static final PartnerConfig CONFIG_LOADING_LOTTIE_ACCOUNT;
    public static final PartnerConfig CONFIG_LOADING_LOTTIE_CONNECTION;
    public static final PartnerConfig CONFIG_LOADING_LOTTIE_DEFAULT;
    public static final PartnerConfig CONFIG_LOADING_LOTTIE_FINAL_HOLD;
    public static final PartnerConfig CONFIG_LOADING_LOTTIE_UPDATE;
    public static final PartnerConfig CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT;
    public static final PartnerConfig CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION;
    public static final PartnerConfig CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT;
    public static final PartnerConfig CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD;
    public static final PartnerConfig CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE;
    public static final PartnerConfig CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT;
    public static final PartnerConfig CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION;
    public static final PartnerConfig CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT;
    public static final PartnerConfig CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD;
    public static final PartnerConfig CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE;
    public static final PartnerConfig CONFIG_NAVIGATION_BAR_BG_COLOR;
    public static final PartnerConfig CONFIG_NAVIGATION_BAR_DIVIDER_COLOR;
    public static final PartnerConfig CONFIG_PROGRESS_BAR_MARGIN_BOTTOM;
    public static final PartnerConfig CONFIG_PROGRESS_BAR_MARGIN_TOP;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_CONNECTION;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_DEFAULT;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD;
    public static final PartnerConfig CONFIG_PROGRESS_ILLUSTRATION_UPDATE;
    public static final PartnerConfig CONFIG_STATUS_BAR_BACKGROUND;

    @Deprecated
    public static final PartnerConfig CONFIG_TRANSITION_TYPE;
    public static final PartnerConfig CONFIG_TWO_PANE_ADAPT_WINDOW_WIDTH;
    private final String resourceName;
    private final ResourceType resourceType;

    public enum ResourceType {
        INTEGER,
        BOOL,
        COLOR,
        DRAWABLE,
        STRING,
        DIMENSION,
        FRACTION,
        ILLUSTRATION,
        STRING_ARRAY
    }

    private static /* synthetic */ PartnerConfig[] $values() {
        return new PartnerConfig[]{CONFIG_STATUS_BAR_BACKGROUND, CONFIG_LIGHT_STATUS_BAR, CONFIG_NAVIGATION_BAR_BG_COLOR, CONFIG_NAVIGATION_BAR_DIVIDER_COLOR, CONFIG_FOOTER_BAR_BG_COLOR, CONFIG_FOOTER_BAR_MORE_TO_SCROLL_BG_COLOR, CONFIG_FOOTER_BAR_MIN_HEIGHT, CONFIG_FOOTER_BAR_PADDING_START, CONFIG_FOOTER_BAR_PADDING_END, CONFIG_LIGHT_NAVIGATION_BAR, CONFIG_FOOTER_BUTTON_FONT_FAMILY, CONFIG_FOOTER_BUTTON_FONT_WEIGHT, CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER, CONFIG_FOOTER_BUTTON_ICON_CANCEL, CONFIG_FOOTER_BUTTON_ICON_CLEAR, CONFIG_FOOTER_BUTTON_ICON_DONE, CONFIG_FOOTER_BUTTON_ICON_NEXT, CONFIG_FOOTER_BUTTON_ICON_OPT_IN, CONFIG_FOOTER_BUTTON_ICON_SKIP, CONFIG_FOOTER_BUTTON_ICON_STOP, CONFIG_FOOTER_BUTTON_PADDING_TOP, CONFIG_FOOTER_BUTTON_PADDING_BOTTOM, CONFIG_FOOTER_BUTTON_RADIUS, CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA, CONFIG_FOOTER_BUTTON_TEXT_SIZE, CONFIG_FOOTER_BUTTON_TEXT_STYLE, CONFIG_FOOTER_BUTTON_MIN_HEIGHT, CONFIG_FOOTER_BUTTON_ALIGNED_END, CONFIG_FOOTER_BUTTON_DISABLED_ALPHA, CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR, CONFIG_FOOTER_PRIMARY_BUTTON_DISABLED_TEXT_COLOR, CONFIG_FOOTER_SECONDARY_BUTTON_DISABLED_TEXT_COLOR, CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR, CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR, CONFIG_FOOTER_PRIMARY_BUTTON_MARGIN_START, CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR, CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR, CONFIG_FOOTER_SECONDARY_BUTTON_MARGIN_START, CONFIG_FOOTER_BUTTON_MIDDLE_SPACE, CONFIG_FOOTER_BUTTON_STACK_MIDDLE_SPACE, CONFIG_LAYOUT_BACKGROUND_COLOR, CONFIG_LAYOUT_MARGIN_START, CONFIG_LAYOUT_MARGIN_END, CONFIG_LAND_MIDDLE_HORIZONTAL_SPACING, CONFIG_HEADER_TEXT_COLOR, CONFIG_HEADER_TEXT_SIZE, CONFIG_HEADER_FONT_FAMILY, CONFIG_HEADER_FONT_WEIGHT, CONFIG_HEADER_FONT_VARIATION_SETTINGS, CONFIG_HEADER_TEXT_MARGIN_TOP, CONFIG_HEADER_TEXT_MARGIN_BOTTOM, CONFIG_LAYOUT_GRAVITY, CONFIG_ICON_MARGIN_TOP, CONFIG_ICON_SIZE, CONFIG_ICON_COLOR, CONFIG_ILLUSTRATION_MAX_WIDTH, CONFIG_ILLUSTRATION_MAX_HEIGHT, CONFIG_HEADER_AREA_BACKGROUND_COLOR, CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM, CONFIG_HEADER_PROGRESS_BAR_COMMON_STYLE, CONFIG_HEADER_AUTO_SIZE_ENABLED, CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE, CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE, CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE, CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA, CONFIG_DESCRIPTION_TEXT_SIZE, CONFIG_DESCRIPTION_TEXT_COLOR, CONFIG_DESCRIPTION_LINK_TEXT_COLOR, CONFIG_DESCRIPTION_FONT_FAMILY, CONFIG_DESCRIPTION_FONT_WEIGHT, CONFIG_DESCRIPTION_LINK_FONT_FAMILY, CONFIG_DESCRIPTION_TEXT_MARGIN_TOP, CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM, CONFIG_ACCOUNT_NAME_TEXT_SIZE, CONFIG_ACCOUNT_NAME_FONT_FAMILY, CONFIG_ACCOUNT_AVATAR_MARGIN_END, CONFIG_ACCOUNT_AVATAR_SIZE, CONFIG_ACCOUNT_CONTAINER_MARGIN_TOP, CONFIG_ACCOUNT_CONTAINER_MARGIN_BOTTOM, CONFIG_CONTENT_TEXT_SIZE, CONFIG_CONTENT_TEXT_COLOR, CONFIG_CONTENT_LINK_TEXT_COLOR, CONFIG_CONTENT_FONT_FAMILY, CONFIG_CONTENT_LAYOUT_GRAVITY, CONFIG_CONTENT_PADDING_TOP, CONFIG_CONTENT_INFO_TEXT_SIZE, CONFIG_CONTENT_INFO_FONT_FAMILY, CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA, CONFIG_CONTENT_INFO_ICON_SIZE, CONFIG_CONTENT_INFO_ICON_MARGIN_END, CONFIG_CONTENT_INFO_PADDING_TOP, CONFIG_CONTENT_INFO_PADDING_BOTTOM, CONFIG_ITEMS_TITLE_TEXT_SIZE, CONFIG_ITEMS_SUMMARY_TEXT_SIZE, CONFIG_ITEMS_SUMMARY_MARGIN_TOP, CONFIG_ITEMS_TITLE_FONT_FAMILY, CONFIG_ITEMS_SUMMARY_FONT_FAMILY, CONFIG_ITEMS_TITLE_FONT_VARIATION_SETTINGS, CONFIG_ITEMS_PADDING_TOP, CONFIG_ITEMS_PADDING_BOTTOM, CONFIG_ITEMS_GROUP_CORNER_RADIUS, CONFIG_ITEMS_MIN_HEIGHT, CONFIG_ITEMS_DIVIDER_SHOWN, CONFIG_CARD_VIEW_INTRINSIC_WIDTH, CONFIG_CARD_VIEW_INTRINSIC_HEIGHT, CONFIG_PROGRESS_ILLUSTRATION_DEFAULT, CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT, CONFIG_PROGRESS_ILLUSTRATION_CONNECTION, CONFIG_PROGRESS_ILLUSTRATION_UPDATE, CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD, CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS, CONFIG_LOADING_LOTTIE_DEFAULT, CONFIG_LOADING_LOTTIE_ACCOUNT, CONFIG_LOADING_LOTTIE_CONNECTION, CONFIG_LOADING_LOTTIE_UPDATE, CONFIG_LOADING_LOTTIE_FINAL_HOLD, CONFIG_TRANSITION_TYPE, CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT, CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT, CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION, CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE, CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD, CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT, CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT, CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION, CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE, CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD, CONFIG_LOADING_LAYOUT_PADDING_TOP, CONFIG_LOADING_LAYOUT_PADDING_START, CONFIG_LOADING_LAYOUT_PADDING_END, CONFIG_LOADING_LAYOUT_PADDING_BOTTOM, CONFIG_LOADING_LAYOUT_HEADER_HEIGHT, CONFIG_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED, CONFIG_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED, CONFIG_PROGRESS_BAR_MARGIN_TOP, CONFIG_PROGRESS_BAR_MARGIN_BOTTOM, CONFIG_TWO_PANE_ADAPT_WINDOW_WIDTH, CONFIG_CARD_VIEW_SELECTED_RADIUS, CONFIG_ASSISTIVE_OPTIONS_PACKAGE_NAME, CONFIG_ASSISTIVE_OPTIONS_ACTIVITY_NAME, CONFIG_ITEMS_BACKGROUND_COLOR, CONFIG_FOOTER_BAR_HIDE_WHEN_IME_SHOWN};
    }

    static {
        ResourceType resourceType = ResourceType.DRAWABLE;
        CONFIG_STATUS_BAR_BACKGROUND = new PartnerConfig("CONFIG_STATUS_BAR_BACKGROUND", 0, PartnerConfigKey.KEY_STATUS_BAR_BACKGROUND, resourceType);
        ResourceType resourceType2 = ResourceType.BOOL;
        CONFIG_LIGHT_STATUS_BAR = new PartnerConfig("CONFIG_LIGHT_STATUS_BAR", 1, PartnerConfigKey.KEY_LIGHT_STATUS_BAR, resourceType2);
        ResourceType resourceType3 = ResourceType.COLOR;
        CONFIG_NAVIGATION_BAR_BG_COLOR = new PartnerConfig("CONFIG_NAVIGATION_BAR_BG_COLOR", 2, PartnerConfigKey.KEY_NAVIGATION_BAR_BG_COLOR, resourceType3);
        CONFIG_NAVIGATION_BAR_DIVIDER_COLOR = new PartnerConfig("CONFIG_NAVIGATION_BAR_DIVIDER_COLOR", 3, PartnerConfigKey.KEY_NAVIGATION_BAR_DIVIDER_COLOR, resourceType3);
        CONFIG_FOOTER_BAR_BG_COLOR = new PartnerConfig("CONFIG_FOOTER_BAR_BG_COLOR", 4, PartnerConfigKey.KEY_FOOTER_BAR_BG_COLOR, resourceType3);
        CONFIG_FOOTER_BAR_MORE_TO_SCROLL_BG_COLOR = new PartnerConfig("CONFIG_FOOTER_BAR_MORE_TO_SCROLL_BG_COLOR", 5, PartnerConfigKey.SETUP_COMPAT_FOOTER_BAR_MORE_TO_SCROLL_BG_COLOR, resourceType3);
        ResourceType resourceType4 = ResourceType.DIMENSION;
        CONFIG_FOOTER_BAR_MIN_HEIGHT = new PartnerConfig("CONFIG_FOOTER_BAR_MIN_HEIGHT", 6, PartnerConfigKey.KEY_FOOTER_BAR_MIN_HEIGHT, resourceType4);
        CONFIG_FOOTER_BAR_PADDING_START = new PartnerConfig("CONFIG_FOOTER_BAR_PADDING_START", 7, PartnerConfigKey.KEY_FOOTER_BAR_PADDING_START, resourceType4);
        CONFIG_FOOTER_BAR_PADDING_END = new PartnerConfig("CONFIG_FOOTER_BAR_PADDING_END", 8, PartnerConfigKey.KEY_FOOTER_BAR_PADDING_END, resourceType4);
        CONFIG_LIGHT_NAVIGATION_BAR = new PartnerConfig("CONFIG_LIGHT_NAVIGATION_BAR", 9, PartnerConfigKey.KEY_LIGHT_NAVIGATION_BAR, resourceType2);
        ResourceType resourceType5 = ResourceType.STRING;
        CONFIG_FOOTER_BUTTON_FONT_FAMILY = new PartnerConfig("CONFIG_FOOTER_BUTTON_FONT_FAMILY", 10, PartnerConfigKey.KEY_FOOTER_BUTTON_FONT_FAMILY, resourceType5);
        ResourceType resourceType6 = ResourceType.INTEGER;
        CONFIG_FOOTER_BUTTON_FONT_WEIGHT = new PartnerConfig("CONFIG_FOOTER_BUTTON_FONT_WEIGHT", 11, PartnerConfigKey.KEY_FOOTER_BUTTON_FONT_WEIGHT, resourceType6);
        CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER", 12, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_ADD_ANOTHER, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_CANCEL = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_CANCEL", 13, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_CANCEL, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_CLEAR = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_CLEAR", 14, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_CLEAR, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_DONE = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_DONE", 15, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_DONE, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_NEXT = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_NEXT", 16, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_NEXT, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_OPT_IN = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_OPT_IN", 17, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_OPT_IN, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_SKIP = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_SKIP", 18, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_SKIP, resourceType);
        CONFIG_FOOTER_BUTTON_ICON_STOP = new PartnerConfig("CONFIG_FOOTER_BUTTON_ICON_STOP", 19, PartnerConfigKey.KEY_FOOTER_BUTTON_ICON_STOP, resourceType);
        CONFIG_FOOTER_BUTTON_PADDING_TOP = new PartnerConfig("CONFIG_FOOTER_BUTTON_PADDING_TOP", 20, PartnerConfigKey.KEY_FOOTER_BUTTON_PADDING_TOP, resourceType4);
        CONFIG_FOOTER_BUTTON_PADDING_BOTTOM = new PartnerConfig("CONFIG_FOOTER_BUTTON_PADDING_BOTTOM", 21, PartnerConfigKey.KEY_FOOTER_BUTTON_PADDING_BOTTOM, resourceType4);
        CONFIG_FOOTER_BUTTON_RADIUS = new PartnerConfig("CONFIG_FOOTER_BUTTON_RADIUS", 22, PartnerConfigKey.KEY_FOOTER_BUTTON_RADIUS, resourceType4);
        ResourceType resourceType7 = ResourceType.FRACTION;
        CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA = new PartnerConfig("CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA", 23, PartnerConfigKey.KEY_FOOTER_BUTTON_RIPPLE_ALPHA, resourceType7);
        CONFIG_FOOTER_BUTTON_TEXT_SIZE = new PartnerConfig("CONFIG_FOOTER_BUTTON_TEXT_SIZE", 24, PartnerConfigKey.KEY_FOOTER_BUTTON_TEXT_SIZE, resourceType4);
        CONFIG_FOOTER_BUTTON_TEXT_STYLE = new PartnerConfig("CONFIG_FOOTER_BUTTON_TEXT_STYLE", 25, PartnerConfigKey.KEY_FOOTER_BUTTON_TEXT_STYLE, resourceType6);
        CONFIG_FOOTER_BUTTON_MIN_HEIGHT = new PartnerConfig("CONFIG_FOOTER_BUTTON_MIN_HEIGHT", 26, PartnerConfigKey.KEY_FOOTER_BUTTON_MIN_HEIGHT, resourceType4);
        CONFIG_FOOTER_BUTTON_ALIGNED_END = new PartnerConfig("CONFIG_FOOTER_BUTTON_ALIGNED_END", 27, PartnerConfigKey.KEY_FOOTER_BUTTON_ALIGNED_END, resourceType2);
        CONFIG_FOOTER_BUTTON_DISABLED_ALPHA = new PartnerConfig("CONFIG_FOOTER_BUTTON_DISABLED_ALPHA", 28, PartnerConfigKey.KEY_FOOTER_BUTTON_DISABLED_ALPHA, resourceType7);
        CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR = new PartnerConfig("CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR", 29, PartnerConfigKey.KEY_FOOTER_BUTTON_DISABLED_BG_COLOR, resourceType3);
        CONFIG_FOOTER_PRIMARY_BUTTON_DISABLED_TEXT_COLOR = new PartnerConfig("CONFIG_FOOTER_PRIMARY_BUTTON_DISABLED_TEXT_COLOR", 30, PartnerConfigKey.KEY_PRIMARY_BUTTON_DISABLED_TEXT_COLOR, resourceType3);
        CONFIG_FOOTER_SECONDARY_BUTTON_DISABLED_TEXT_COLOR = new PartnerConfig("CONFIG_FOOTER_SECONDARY_BUTTON_DISABLED_TEXT_COLOR", 31, PartnerConfigKey.KEY_SECONDARY_BUTTON_DISABLED_TEXT_COLOR, resourceType3);
        CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR = new PartnerConfig("CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR", 32, PartnerConfigKey.KEY_FOOTER_PRIMARY_BUTTON_BG_COLOR, resourceType3);
        CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR = new PartnerConfig("CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR", 33, PartnerConfigKey.KEY_FOOTER_PRIMARY_BUTTON_TEXT_COLOR, resourceType3);
        CONFIG_FOOTER_PRIMARY_BUTTON_MARGIN_START = new PartnerConfig("CONFIG_FOOTER_PRIMARY_BUTTON_MARGIN_START", 34, PartnerConfigKey.KEY_FOOTER_PRIMARY_BUTTON_MARGIN_START, resourceType4);
        CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR = new PartnerConfig("CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR", 35, PartnerConfigKey.KEY_FOOTER_SECONDARY_BUTTON_BG_COLOR, resourceType3);
        CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR = new PartnerConfig("CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR", 36, PartnerConfigKey.KEY_FOOTER_SECONDARY_BUTTON_TEXT_COLOR, resourceType3);
        CONFIG_FOOTER_SECONDARY_BUTTON_MARGIN_START = new PartnerConfig("CONFIG_FOOTER_SECONDARY_BUTTON_MARGIN_START", 37, PartnerConfigKey.KEY_FOOTER_SECONDARY_BUTTON_MARGIN_START, resourceType4);
        CONFIG_FOOTER_BUTTON_MIDDLE_SPACE = new PartnerConfig("CONFIG_FOOTER_BUTTON_MIDDLE_SPACE", 38, PartnerConfigKey.KEY_FOOTER_BUTTON_MIDDLE_SPACE, resourceType4);
        CONFIG_FOOTER_BUTTON_STACK_MIDDLE_SPACE = new PartnerConfig("CONFIG_FOOTER_BUTTON_STACK_MIDDLE_SPACE", 39, PartnerConfigKey.KEY_FOOTER_BUTTON_STACK_MIDDLE_SPACE, resourceType4);
        CONFIG_LAYOUT_BACKGROUND_COLOR = new PartnerConfig("CONFIG_LAYOUT_BACKGROUND_COLOR", 40, PartnerConfigKey.KEY_LAYOUT_BACKGROUND_COLOR, resourceType3);
        CONFIG_LAYOUT_MARGIN_START = new PartnerConfig("CONFIG_LAYOUT_MARGIN_START", 41, PartnerConfigKey.KEY_LAYOUT_MARGIN_START, resourceType4);
        CONFIG_LAYOUT_MARGIN_END = new PartnerConfig("CONFIG_LAYOUT_MARGIN_END", 42, PartnerConfigKey.KEY_LAYOUT_MARGIN_END, resourceType4);
        CONFIG_LAND_MIDDLE_HORIZONTAL_SPACING = new PartnerConfig("CONFIG_LAND_MIDDLE_HORIZONTAL_SPACING", 43, PartnerConfigKey.KEY_LAND_MIDDLE_HORIZONTAL_SPACING, resourceType4);
        CONFIG_HEADER_TEXT_COLOR = new PartnerConfig("CONFIG_HEADER_TEXT_COLOR", 44, PartnerConfigKey.KEY_HEADER_TEXT_COLOR, resourceType3);
        CONFIG_HEADER_TEXT_SIZE = new PartnerConfig("CONFIG_HEADER_TEXT_SIZE", 45, PartnerConfigKey.KEY_HEADER_TEXT_SIZE, resourceType4);
        CONFIG_HEADER_FONT_FAMILY = new PartnerConfig("CONFIG_HEADER_FONT_FAMILY", 46, PartnerConfigKey.KEY_HEADER_FONT_FAMILY, resourceType5);
        CONFIG_HEADER_FONT_WEIGHT = new PartnerConfig("CONFIG_HEADER_FONT_WEIGHT", 47, PartnerConfigKey.KEY_HEADER_FONT_WEIGHT, resourceType6);
        CONFIG_HEADER_FONT_VARIATION_SETTINGS = new PartnerConfig("CONFIG_HEADER_FONT_VARIATION_SETTINGS", 48, PartnerConfigKey.KEY_HEADER_FONT_VARIATION_SETTINGS, resourceType5);
        CONFIG_HEADER_TEXT_MARGIN_TOP = new PartnerConfig("CONFIG_HEADER_TEXT_MARGIN_TOP", 49, PartnerConfigKey.KEY_HEADER_TEXT_MARGIN_TOP, resourceType4);
        CONFIG_HEADER_TEXT_MARGIN_BOTTOM = new PartnerConfig("CONFIG_HEADER_TEXT_MARGIN_BOTTOM", 50, PartnerConfigKey.KEY_HEADER_TEXT_MARGIN_BOTTOM, resourceType4);
        CONFIG_LAYOUT_GRAVITY = new PartnerConfig("CONFIG_LAYOUT_GRAVITY", 51, PartnerConfigKey.KEY_LAYOUT_GRAVITY, resourceType5);
        CONFIG_ICON_MARGIN_TOP = new PartnerConfig("CONFIG_ICON_MARGIN_TOP", 52, PartnerConfigKey.KEY_ICON_MARGIN_TOP, resourceType4);
        CONFIG_ICON_SIZE = new PartnerConfig("CONFIG_ICON_SIZE", 53, PartnerConfigKey.KEY_ICON_SIZE, resourceType4);
        CONFIG_ICON_COLOR = new PartnerConfig("CONFIG_ICON_COLOR", 54, PartnerConfigKey.KEY_ICON_COLOR, resourceType3);
        CONFIG_ILLUSTRATION_MAX_WIDTH = new PartnerConfig("CONFIG_ILLUSTRATION_MAX_WIDTH", 55, PartnerConfigKey.KEY_ILLUSTRATION_MAX_WIDTH, resourceType4);
        CONFIG_ILLUSTRATION_MAX_HEIGHT = new PartnerConfig("CONFIG_ILLUSTRATION_MAX_HEIGHT", 56, PartnerConfigKey.KEY_ILLUSTRATION_MAX_HEIGHT, resourceType4);
        CONFIG_HEADER_AREA_BACKGROUND_COLOR = new PartnerConfig("CONFIG_HEADER_AREA_BACKGROUND_COLOR", 57, PartnerConfigKey.KEY_HEADER_AREA_BACKGROUND_COLOR, resourceType3);
        CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM = new PartnerConfig("CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM", 58, PartnerConfigKey.KEY_HEADER_CONTAINER_MARGIN_BOTTOM, resourceType4);
        CONFIG_HEADER_PROGRESS_BAR_COMMON_STYLE = new PartnerConfig("CONFIG_HEADER_PROGRESS_BAR_COMMON_STYLE", 59, PartnerConfigKey.KEY_HEADER_PROGRESS_BAR_COMMON_STYLE, resourceType2);
        CONFIG_HEADER_AUTO_SIZE_ENABLED = new PartnerConfig("CONFIG_HEADER_AUTO_SIZE_ENABLED", 60, PartnerConfigKey.KEY_HEADER_AUTO_SIZE_ENABLED, resourceType2);
        CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE = new PartnerConfig("CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE", 61, PartnerConfigKey.KEY_HEADER_AUTO_SIZE_MAX_TEXT_SIZE, resourceType4);
        CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE = new PartnerConfig("CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE", 62, PartnerConfigKey.KEY_HEADER_AUTO_SIZE_MIN_TEXT_SIZE, resourceType4);
        CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE = new PartnerConfig("CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE", 63, PartnerConfigKey.KEY_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE, resourceType6);
        CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA = new PartnerConfig("CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA", 64, PartnerConfigKey.KEY_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA, resourceType4);
        CONFIG_DESCRIPTION_TEXT_SIZE = new PartnerConfig("CONFIG_DESCRIPTION_TEXT_SIZE", 65, PartnerConfigKey.KEY_DESCRIPTION_TEXT_SIZE, resourceType4);
        CONFIG_DESCRIPTION_TEXT_COLOR = new PartnerConfig("CONFIG_DESCRIPTION_TEXT_COLOR", 66, PartnerConfigKey.KEY_DESCRIPTION_TEXT_COLOR, resourceType3);
        CONFIG_DESCRIPTION_LINK_TEXT_COLOR = new PartnerConfig("CONFIG_DESCRIPTION_LINK_TEXT_COLOR", 67, PartnerConfigKey.KEY_DESCRIPTION_LINK_TEXT_COLOR, resourceType3);
        CONFIG_DESCRIPTION_FONT_FAMILY = new PartnerConfig("CONFIG_DESCRIPTION_FONT_FAMILY", 68, PartnerConfigKey.KEY_DESCRIPTION_FONT_FAMILY, resourceType5);
        CONFIG_DESCRIPTION_FONT_WEIGHT = new PartnerConfig("CONFIG_DESCRIPTION_FONT_WEIGHT", 69, PartnerConfigKey.KEY_DESCRIPTION_FONT_WEIGHT, resourceType6);
        CONFIG_DESCRIPTION_LINK_FONT_FAMILY = new PartnerConfig("CONFIG_DESCRIPTION_LINK_FONT_FAMILY", 70, PartnerConfigKey.KEY_DESCRIPTION_LINK_FONT_FAMILY, resourceType5);
        CONFIG_DESCRIPTION_TEXT_MARGIN_TOP = new PartnerConfig("CONFIG_DESCRIPTION_TEXT_MARGIN_TOP", 71, PartnerConfigKey.KEY_DESCRIPTION_TEXT_MARGIN_TOP, resourceType4);
        CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM = new PartnerConfig("CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM", 72, PartnerConfigKey.KEY_DESCRIPTION_TEXT_MARGIN_BOTTOM, resourceType4);
        CONFIG_ACCOUNT_NAME_TEXT_SIZE = new PartnerConfig("CONFIG_ACCOUNT_NAME_TEXT_SIZE", 73, PartnerConfigKey.KEY_ACCOUNT_NAME_TEXT_SIZE, resourceType4);
        CONFIG_ACCOUNT_NAME_FONT_FAMILY = new PartnerConfig("CONFIG_ACCOUNT_NAME_FONT_FAMILY", 74, PartnerConfigKey.KEY_ACCOUNT_NAME_FONT_FAMILY, resourceType5);
        CONFIG_ACCOUNT_AVATAR_MARGIN_END = new PartnerConfig("CONFIG_ACCOUNT_AVATAR_MARGIN_END", 75, PartnerConfigKey.KEY_ACCOUNT_AVATAR_MARGIN_END, resourceType4);
        CONFIG_ACCOUNT_AVATAR_SIZE = new PartnerConfig("CONFIG_ACCOUNT_AVATAR_SIZE", 76, PartnerConfigKey.KEY_ACCOUNT_AVATAR_MAX_SIZE, resourceType4);
        CONFIG_ACCOUNT_CONTAINER_MARGIN_TOP = new PartnerConfig("CONFIG_ACCOUNT_CONTAINER_MARGIN_TOP", 77, PartnerConfigKey.KEY_ACCOUNT_CONTAINER_MARGIN_TOP, resourceType4);
        CONFIG_ACCOUNT_CONTAINER_MARGIN_BOTTOM = new PartnerConfig("CONFIG_ACCOUNT_CONTAINER_MARGIN_BOTTOM", 78, PartnerConfigKey.KEY_ACCOUNT_CONTAINER_MARGIN_BOTTOM, resourceType4);
        CONFIG_CONTENT_TEXT_SIZE = new PartnerConfig("CONFIG_CONTENT_TEXT_SIZE", 79, PartnerConfigKey.KEY_CONTENT_TEXT_SIZE, resourceType4);
        CONFIG_CONTENT_TEXT_COLOR = new PartnerConfig("CONFIG_CONTENT_TEXT_COLOR", 80, PartnerConfigKey.KEY_CONTENT_TEXT_COLOR, resourceType3);
        CONFIG_CONTENT_LINK_TEXT_COLOR = new PartnerConfig("CONFIG_CONTENT_LINK_TEXT_COLOR", 81, PartnerConfigKey.KEY_CONTENT_LINK_TEXT_COLOR, resourceType3);
        CONFIG_CONTENT_FONT_FAMILY = new PartnerConfig("CONFIG_CONTENT_FONT_FAMILY", 82, PartnerConfigKey.KEY_CONTENT_FONT_FAMILY, resourceType5);
        CONFIG_CONTENT_LAYOUT_GRAVITY = new PartnerConfig("CONFIG_CONTENT_LAYOUT_GRAVITY", 83, PartnerConfigKey.KEY_CONTENT_LAYOUT_GRAVITY, resourceType5);
        CONFIG_CONTENT_PADDING_TOP = new PartnerConfig("CONFIG_CONTENT_PADDING_TOP", 84, PartnerConfigKey.KEY_CONTENT_PADDING_TOP, resourceType4);
        CONFIG_CONTENT_INFO_TEXT_SIZE = new PartnerConfig("CONFIG_CONTENT_INFO_TEXT_SIZE", 85, PartnerConfigKey.KEY_CONTENT_INFO_TEXT_SIZE, resourceType4);
        CONFIG_CONTENT_INFO_FONT_FAMILY = new PartnerConfig("CONFIG_CONTENT_INFO_FONT_FAMILY", 86, PartnerConfigKey.KEY_CONTENT_INFO_FONT_FAMILY, resourceType5);
        CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA = new PartnerConfig("CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA", 87, PartnerConfigKey.KEY_CONTENT_INFO_LINE_SPACING_EXTRA, resourceType4);
        CONFIG_CONTENT_INFO_ICON_SIZE = new PartnerConfig("CONFIG_CONTENT_INFO_ICON_SIZE", 88, PartnerConfigKey.KEY_CONTENT_INFO_ICON_SIZE, resourceType4);
        CONFIG_CONTENT_INFO_ICON_MARGIN_END = new PartnerConfig("CONFIG_CONTENT_INFO_ICON_MARGIN_END", 89, PartnerConfigKey.KEY_CONTENT_INFO_ICON_MARGIN_END, resourceType4);
        CONFIG_CONTENT_INFO_PADDING_TOP = new PartnerConfig("CONFIG_CONTENT_INFO_PADDING_TOP", 90, PartnerConfigKey.KEY_CONTENT_INFO_PADDING_TOP, resourceType4);
        CONFIG_CONTENT_INFO_PADDING_BOTTOM = new PartnerConfig("CONFIG_CONTENT_INFO_PADDING_BOTTOM", 91, PartnerConfigKey.KEY_CONTENT_INFO_PADDING_BOTTOM, resourceType4);
        CONFIG_ITEMS_TITLE_TEXT_SIZE = new PartnerConfig("CONFIG_ITEMS_TITLE_TEXT_SIZE", 92, PartnerConfigKey.KEY_ITEMS_TITLE_TEXT_SIZE, resourceType4);
        CONFIG_ITEMS_SUMMARY_TEXT_SIZE = new PartnerConfig("CONFIG_ITEMS_SUMMARY_TEXT_SIZE", 93, PartnerConfigKey.KEY_ITEMS_SUMMARY_TEXT_SIZE, resourceType4);
        CONFIG_ITEMS_SUMMARY_MARGIN_TOP = new PartnerConfig("CONFIG_ITEMS_SUMMARY_MARGIN_TOP", 94, PartnerConfigKey.KEY_ITEMS_SUMMARY_MARGIN_TOP, resourceType4);
        CONFIG_ITEMS_TITLE_FONT_FAMILY = new PartnerConfig("CONFIG_ITEMS_TITLE_FONT_FAMILY", 95, PartnerConfigKey.KEY_ITEMS_TITLE_FONT_FAMILY, resourceType5);
        CONFIG_ITEMS_SUMMARY_FONT_FAMILY = new PartnerConfig("CONFIG_ITEMS_SUMMARY_FONT_FAMILY", 96, PartnerConfigKey.KEY_ITEMS_SUMMARY_FONT_FAMILY, resourceType5);
        CONFIG_ITEMS_TITLE_FONT_VARIATION_SETTINGS = new PartnerConfig("CONFIG_ITEMS_TITLE_FONT_VARIATION_SETTINGS", 97, PartnerConfigKey.KEY_ITEMS_TITLE_FONT_VARIATION_SETTINGS, resourceType5);
        CONFIG_ITEMS_PADDING_TOP = new PartnerConfig("CONFIG_ITEMS_PADDING_TOP", 98, PartnerConfigKey.KEY_ITEMS_PADDING_TOP, resourceType4);
        CONFIG_ITEMS_PADDING_BOTTOM = new PartnerConfig("CONFIG_ITEMS_PADDING_BOTTOM", 99, PartnerConfigKey.KEY_ITEMS_PADDING_BOTTOM, resourceType4);
        CONFIG_ITEMS_GROUP_CORNER_RADIUS = new PartnerConfig("CONFIG_ITEMS_GROUP_CORNER_RADIUS", 100, PartnerConfigKey.KEY_ITEMS_GROUP_CORNER_RADIUS, resourceType4);
        CONFIG_ITEMS_MIN_HEIGHT = new PartnerConfig("CONFIG_ITEMS_MIN_HEIGHT", 101, PartnerConfigKey.KEY_ITEMS_MIN_HEIGHT, resourceType4);
        CONFIG_ITEMS_DIVIDER_SHOWN = new PartnerConfig("CONFIG_ITEMS_DIVIDER_SHOWN", 102, PartnerConfigKey.KEY_ITEMS_DIVIDER_SHOWN, resourceType2);
        CONFIG_CARD_VIEW_INTRINSIC_WIDTH = new PartnerConfig("CONFIG_CARD_VIEW_INTRINSIC_WIDTH", 103, PartnerConfigKey.KEY_CARD_VIEW_INTRINSIC_WIDTH, resourceType4);
        CONFIG_CARD_VIEW_INTRINSIC_HEIGHT = new PartnerConfig("CONFIG_CARD_VIEW_INTRINSIC_HEIGHT", 104, PartnerConfigKey.KEY_CARD_VIEW_INTRINSIC_HEIGHT, resourceType4);
        ResourceType resourceType8 = ResourceType.ILLUSTRATION;
        CONFIG_PROGRESS_ILLUSTRATION_DEFAULT = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_DEFAULT", 105, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_DEFAULT, resourceType8);
        CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT", 106, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_ACCOUNT, resourceType8);
        CONFIG_PROGRESS_ILLUSTRATION_CONNECTION = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_CONNECTION", 107, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_CONNECTION, resourceType8);
        CONFIG_PROGRESS_ILLUSTRATION_UPDATE = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_UPDATE", 108, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_UPDATE, resourceType8);
        CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD", 109, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_FINAL_HOLD, resourceType8);
        CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS = new PartnerConfig("CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS", 110, PartnerConfigKey.KEY_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS, resourceType6);
        CONFIG_LOADING_LOTTIE_DEFAULT = new PartnerConfig("CONFIG_LOADING_LOTTIE_DEFAULT", 111, PartnerConfigKey.KEY_LOADING_LOTTIE_DEFAULT, resourceType8);
        CONFIG_LOADING_LOTTIE_ACCOUNT = new PartnerConfig("CONFIG_LOADING_LOTTIE_ACCOUNT", 112, PartnerConfigKey.KEY_LOADING_LOTTIE_ACCOUNT, resourceType8);
        CONFIG_LOADING_LOTTIE_CONNECTION = new PartnerConfig("CONFIG_LOADING_LOTTIE_CONNECTION", 113, PartnerConfigKey.KEY_LOADING_LOTTIE_CONNECTION, resourceType8);
        CONFIG_LOADING_LOTTIE_UPDATE = new PartnerConfig("CONFIG_LOADING_LOTTIE_UPDATE", 114, PartnerConfigKey.KEY_LOADING_LOTTIE_UPDATE, resourceType8);
        CONFIG_LOADING_LOTTIE_FINAL_HOLD = new PartnerConfig("CONFIG_LOADING_LOTTIE_FINAL_HOLD", 115, PartnerConfigKey.KEY_LOADING_LOTTIE_FINAL_HOLD, resourceType8);
        CONFIG_TRANSITION_TYPE = new PartnerConfig("CONFIG_TRANSITION_TYPE", 116, PartnerConfigKey.KEY_TRANSITION_TYPE, resourceType6);
        ResourceType resourceType9 = ResourceType.STRING_ARRAY;
        CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT = new PartnerConfig("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT", 117, PartnerConfigKey.KEY_LOADING_LIGHT_THEME_CUSTOMIZATION_DEFAULT, resourceType9);
        CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT = new PartnerConfig("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT", 118, PartnerConfigKey.KEY_LOADING_LIGHT_THEME_CUSTOMIZATION_ACCOUNT, resourceType9);
        CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION = new PartnerConfig("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION", 119, PartnerConfigKey.KEY_LOADING_LIGHT_THEME_CUSTOMIZATION_CONNECTION, resourceType9);
        CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE = new PartnerConfig("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE", 120, PartnerConfigKey.KEY_LOADING_LIGHT_THEME_CUSTOMIZATION_UPDATE, resourceType9);
        CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD = new PartnerConfig("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD", 121, PartnerConfigKey.KEY_LOADING_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD, resourceType9);
        CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT = new PartnerConfig("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT", 122, PartnerConfigKey.KEY_LOADING_DARK_THEME_CUSTOMIZATION_DEFAULT, resourceType9);
        CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT = new PartnerConfig("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT", 123, PartnerConfigKey.KEY_LOADING_DARK_THEME_CUSTOMIZATION_ACCOUNT, resourceType9);
        CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION = new PartnerConfig("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION", 124, PartnerConfigKey.KEY_LOADING_DARK_THEME_CUSTOMIZATION_CONNECTION, resourceType9);
        CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE = new PartnerConfig("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE", 125, PartnerConfigKey.KEY_LOADING_DARK_THEME_CUSTOMIZATION_UPDATE, resourceType9);
        CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD = new PartnerConfig("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD", 126, PartnerConfigKey.KEY_LOADING_DARK_THEME_CUSTOMIZATION_FINAL_HOLD, resourceType9);
        CONFIG_LOADING_LAYOUT_PADDING_TOP = new PartnerConfig("CONFIG_LOADING_LAYOUT_PADDING_TOP", 127, PartnerConfigKey.KEY_LOADING_LAYOUT_CONTENT_PADDING_TOP, resourceType4);
        CONFIG_LOADING_LAYOUT_PADDING_START = new PartnerConfig("CONFIG_LOADING_LAYOUT_PADDING_START", 128, PartnerConfigKey.KEY_LOADING_LAYOUT_CONTENT_PADDING_START, resourceType4);
        CONFIG_LOADING_LAYOUT_PADDING_END = new PartnerConfig("CONFIG_LOADING_LAYOUT_PADDING_END", 129, PartnerConfigKey.KEY_LOADING_LAYOUT_CONTENT_PADDING_END, resourceType4);
        CONFIG_LOADING_LAYOUT_PADDING_BOTTOM = new PartnerConfig("CONFIG_LOADING_LAYOUT_PADDING_BOTTOM", 130, PartnerConfigKey.KEY_LOADING_LAYOUT_CONTENT_PADDING_BOTTOM, resourceType4);
        CONFIG_LOADING_LAYOUT_HEADER_HEIGHT = new PartnerConfig("CONFIG_LOADING_LAYOUT_HEADER_HEIGHT", 131, PartnerConfigKey.KEY_LOADING_LAYOUT_HEADER_HEIGHT, resourceType4);
        CONFIG_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED = new PartnerConfig("CONFIG_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED", 132, PartnerConfigKey.KEY_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED, resourceType2);
        CONFIG_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED = new PartnerConfig("CONFIG_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED", 133, PartnerConfigKey.KEY_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED, resourceType2);
        CONFIG_PROGRESS_BAR_MARGIN_TOP = new PartnerConfig("CONFIG_PROGRESS_BAR_MARGIN_TOP", 134, PartnerConfigKey.KEY_PROGRESS_BAR_MARGIN_TOP, resourceType4);
        CONFIG_PROGRESS_BAR_MARGIN_BOTTOM = new PartnerConfig("CONFIG_PROGRESS_BAR_MARGIN_BOTTOM", 135, PartnerConfigKey.KEY_PROGRESS_BAR_MARGIN_BOTTOM, resourceType4);
        CONFIG_TWO_PANE_ADAPT_WINDOW_WIDTH = new PartnerConfig("CONFIG_TWO_PANE_ADAPT_WINDOW_WIDTH", 136, PartnerConfigKey.KEY_TWO_PANE_ADAPT_WINDOW_WIDTH, resourceType6);
        CONFIG_CARD_VIEW_SELECTED_RADIUS = new PartnerConfig("CONFIG_CARD_VIEW_SELECTED_RADIUS", 137, PartnerConfigKey.KEY_CARD_VIEW_SELECTED_RADIUS, resourceType4);
        CONFIG_ASSISTIVE_OPTIONS_PACKAGE_NAME = new PartnerConfig("CONFIG_ASSISTIVE_OPTIONS_PACKAGE_NAME", 138, PartnerConfigKey.KEY_ASSISTIVE_OPTIONS_PACKAGE_NAME, resourceType5);
        CONFIG_ASSISTIVE_OPTIONS_ACTIVITY_NAME = new PartnerConfig("CONFIG_ASSISTIVE_OPTIONS_ACTIVITY_NAME", 139, PartnerConfigKey.KEY_ASSISTIVE_OPTIONS_ACTIVITY_NAME, resourceType5);
        CONFIG_ITEMS_BACKGROUND_COLOR = new PartnerConfig("CONFIG_ITEMS_BACKGROUND_COLOR", 140, PartnerConfigKey.KEY_ITEMS_BACKGROUND_COLOR, resourceType3);
        CONFIG_FOOTER_BAR_HIDE_WHEN_IME_SHOWN = new PartnerConfig("CONFIG_FOOTER_BAR_HIDE_WHEN_IME_SHOWN", 141, PartnerConfigKey.KEY_FOOTER_BAR_HIDE_WHEN_IME_SHOWN, resourceType2);
        $VALUES = $values();
    }

    private PartnerConfig(String str, int i3, String str2, ResourceType resourceType) {
        super(str, i3);
        this.resourceName = str2;
        this.resourceType = resourceType;
    }

    public static PartnerConfig valueOf(String str) {
        return (PartnerConfig) Enum.valueOf(PartnerConfig.class, str);
    }

    public static PartnerConfig[] values() {
        return (PartnerConfig[]) $VALUES.clone();
    }

    public String getResourceName() {
        return this.resourceName;
    }

    public ResourceType getResourceType() {
        return this.resourceType;
    }
}
