#!/usr/bin/env python3
"""Generate JamoTables.java from Unicode character names.

Every conjoining jamo (U+1100-11FF, U+A960-A97F, U+D7B0-D7FF) and every
compatibility jamo (U+3131-318E) is mapped to the sequence of *base letters*
(single keyboard letters) its Unicode name spells out, e.g.
  U+1122 HANGUL CHOSEONG PIEUP-SIOS-KIYEOK -> "ㅂㅅㄱ"
  U+11A2 HANGUL JUNGSEONG SSANGARAEA       -> "ㆍㆍ"
"""
import sys
import unicodedata

CONS = {
    "KIYEOK": "ㄱ", "NIEUN": "ㄴ", "TIKEUT": "ㄷ", "RIEUL": "ㄹ", "MIEUM": "ㅁ",
    "PIEUP": "ㅂ", "SIOS": "ㅅ", "IEUNG": "ㅇ", "CIEUC": "ㅈ", "CHIEUCH": "ㅊ",
    "KHIEUKH": "ㅋ", "THIEUTH": "ㅌ", "PHIEUPH": "ㅍ", "HIEUH": "ㅎ",
    "PANSIOS": "ㅿ", "YESIEUNG": "ㆁ", "YEORINHIEUH": "ㆆ",
}
VOW = {
    "A": "ㅏ", "AE": "ㅐ", "YA": "ㅑ", "YAE": "ㅒ", "EO": "ㅓ", "E": "ㅔ",
    "YEO": "ㅕ", "YE": "ㅖ", "O": "ㅗ", "WA": "ㅗㅏ", "WAE": "ㅗㅐ", "OE": "ㅗㅣ",
    "YO": "ㅛ", "U": "ㅜ", "WEO": "ㅜㅓ", "WE": "ㅜㅔ", "WI": "ㅜㅣ", "YU": "ㅠ",
    "EU": "ㅡ", "YI": "ㅡㅣ", "I": "ㅣ", "ARAEA": "ㆍ", "SSANGARAEA": "ㆍㆍ",
    "ARAEAE": "ㆍㅣ",
}


# 치두음 / 정치음 initials (U+113C..1155): single keys of the Old Korean IME's Shift layer.
# Unicode spells them CHITUEUM+SIOS ..., so they are base letters, not clusters.
TOOTH = {
    "CHITUEUM": {"SIOS": "ᄼ", "CIEUC": "ᅎ", "CHIEUCH": "ᅔ"},
    "CEONGCHIEUM": {"SIOS": "ᄾ", "CIEUC": "ᅐ", "CHIEUCH": "ᅕ"},
}


def cons_part(p):
    for prefix, table in TOOTH.items():
        if p.startswith(prefix):
            rest = p[len(prefix):]
            if rest.startswith("SSANG"):
                base = table.get(rest[5:])
                return None if base is None else base * 2
            return table.get(rest)
    if p.startswith("SSANG"):
        b = cons_part(p[5:])
        return None if b is None else b * 2
    if p.startswith("KAPYEOUN"):
        b = cons_part(p[8:])
        return None if b is None else b + "ㅇ"
    return CONS.get(p)


def spell(name, vowel):
    out = ""
    for p in name.split("-"):
        s = VOW.get(p) if vowel else cons_part(p)
        if s is None:
            return None
        out += s
    return out


def collect():
    lead, vowel, tail, compat = {}, {}, {}, {}
    ranges = [range(0x1100, 0x1200), range(0xA960, 0xA980), range(0xD7B0, 0xD800),
              range(0x3131, 0x318F)]
    for r in ranges:
        for cp in r:
            n = unicodedata.name(chr(cp), "")
            for prefix, table, is_vowel in (
                    ("HANGUL CHOSEONG ", lead, False),
                    ("HANGUL JUNGSEONG ", vowel, True),
                    ("HANGUL JONGSEONG ", tail, False)):
                if n.startswith(prefix):
                    s = spell(n[len(prefix):], is_vowel)
                    if s:
                        table.setdefault(s, cp)
            if n.startswith("HANGUL LETTER "):
                rest = n[len("HANGUL LETTER "):]
                s = spell(rest, True) if rest in VOW or all(p in VOW for p in rest.split("-")) \
                    else spell(rest, False)
                if s:
                    compat.setdefault(s, cp)
    return lead, vowel, tail, compat


def java_map(name, table):
    keys = "".join(k + "\\u0000" for k in table)
    vals = "".join("\\u%04X" % v for v in table.values())
    return (f'    static final String {name}_KEYS = "{keys}";\n'
            f'    static final String {name}_VALUES = "{vals}";\n')


def main():
    lead, vowel, tail, compat = collect()
    body = ("// Generated by tools/gen_jamo_tables.py. Do not edit by hand.\n"
            "package io.github.wnsdn517.oldhangul.engine;\n\n"
            "/** Base-letter spelling -> jamo, split on NUL. */\n"
            "final class JamoTables {\n"
            "    private JamoTables() {}\n\n"
            + java_map("LEADING", lead) + java_map("VOWEL", vowel)
            + java_map("TRAILING", tail) + java_map("COMPAT", compat) + "}\n")
    sys.stdout.write(body)


if __name__ == "__main__":
    main()
