package Um;

import java.util.ArrayList;

/* JADX INFO: loaded from: classes3.dex */
public abstract class g {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final ArrayList f11691a;

    static {
        ArrayList arrayList = new ArrayList();
        f11691a = arrayList;
        A2.a.t(arrayList, "😀", "😃", "😄", "😁");
        A2.a.t(arrayList, "😆", "😅", "🤣", "😂");
        A2.a.t(arrayList, "🙂", "🙃", "🫠", "😉");
        A2.a.t(arrayList, "😊", "😇", "🥰", "😍");
        A2.a.t(arrayList, "🤩", "😘", "😗", "☺️");
        A2.a.t(arrayList, "😚", "😙", "🥲", "😋");
        A2.a.t(arrayList, "😛", "😜", "🤪", "😝");
        A2.a.t(arrayList, "🤑", "🤗", "🤭", "🫢");
        A2.a.t(arrayList, "🫣", "🤫", "🤔", "🫡");
        A2.a.t(arrayList, "🤐", "🤨", "😐", "😑");
        A2.a.t(arrayList, "😶", "🫥", "😶\u200d🌫️", "😏");
        A2.a.t(arrayList, "😒", "🙄", "😬", "😮\u200d💨");
        A2.a.t(arrayList, "🤥", "🫨", "😌", "😔");
        A2.a.t(arrayList, "😪", "🤤", "😴", "😷");
        A2.a.t(arrayList, "🤒", "🤕", "🤢", "🤮");
        A2.a.t(arrayList, "🤧", "🥵", "🥶", "🥴");
        A2.a.t(arrayList, "😵", "😵\u200d💫", "🤯", "🤠");
        A2.a.t(arrayList, "🥳", "🥸", "😎", "🤓");
        A2.a.t(arrayList, "🧐", "😕", "🫤", "😟");
        A2.a.t(arrayList, "🙁", "☹️", "😮", "😯");
        A2.a.t(arrayList, "😲", "😳", "🥺", "🥹");
        A2.a.t(arrayList, "😦", "😧", "😨", "😰");
        A2.a.t(arrayList, "😥", "😢", "😭", "😱");
        A2.a.t(arrayList, "😖", "😣", "😞", "😓");
        A2.a.t(arrayList, "😩", "😫", "🥱", "😤");
        A2.a.t(arrayList, "😡", "😠", "🤬", "😈");
        A2.a.t(arrayList, "👿", "💀", "☠️", "💩");
        A2.a.t(arrayList, "🤡", "👹", "👺", "👻");
        A2.a.t(arrayList, "👽", "👾", "🤖", "😺");
        A2.a.t(arrayList, "😸", "😹", "😻", "😼");
        A2.a.t(arrayList, "😽", "🙀", "😿", "😾");
        A2.a.t(arrayList, "🙈", "🙉", "🙊", "💋");
        A2.a.t(arrayList, "💌", "💘", "💝", "💖");
        A2.a.t(arrayList, "💗", "💓", "💞", "💕");
        A2.a.t(arrayList, "💟", "❣️", "💔", "❤️\u200d🔥");
        A2.a.t(arrayList, "❤️\u200d🩹", "❤️", "🩷", "🧡");
        A2.a.t(arrayList, "💛", "💚", "💙", "🩵");
        A2.a.t(arrayList, "💜", "🤎", "🖤", "🩶");
        A2.a.t(arrayList, "🤍", "💯", "💢", "💥");
        A2.a.t(arrayList, "💫", "💦", "💨", "🕳");
        A2.a.t(arrayList, "💣", "💬", "🗨", "🗯");
        A2.a.t(arrayList, "💭", "💤", "👋", "🤚");
        A2.a.t(arrayList, "🖐", "✋️", "🖖", "🫱");
        A2.a.t(arrayList, "🫲", "🫳", "🫴", "🫷");
        A2.a.t(arrayList, "🫸", "👌", "🤌", "🤏");
        A2.a.t(arrayList, "✌️", "🤞", "🫰", "🤟");
        A2.a.t(arrayList, "🤘", "🤙", "👈", "👉");
        A2.a.t(arrayList, "👆", "🖕", "👇", "☝️");
        A2.a.t(arrayList, "🫵", "👍", "👎", "✊️");
        A2.a.t(arrayList, "👊", "🤛", "🤜", "👏");
        A2.a.t(arrayList, "🙌", "🫶", "👐", "🤲");
        A2.a.t(arrayList, "🤝", "🙏", "✍️", "💅");
        A2.a.t(arrayList, "🤳", "💪", "🦾", "🦿");
        A2.a.t(arrayList, "🦵", "🦶", "👂", "🦻");
        A2.a.t(arrayList, "👃", "🧠", "🫀", "🫁");
        A2.a.t(arrayList, "🦷", "🦴", "👀", "👁");
        A2.a.t(arrayList, "👅", "👄", "🫦", "👶");
        A2.a.t(arrayList, "🧒", "👦", "👧", "🧑");
        A2.a.t(arrayList, "👱", "👨", "🧔\u200d♂️", "🧔\u200d♀️");
        A2.a.t(arrayList, "🧔", "👨\u200d🦰", "👨\u200d🦱", "👨\u200d🦳");
        A2.a.t(arrayList, "👨\u200d🦲", "👩", "👩\u200d🦰", "🧑\u200d🦰");
        A2.a.t(arrayList, "👩\u200d🦱", "🧑\u200d🦱", "👩\u200d🦳", "🧑\u200d🦳");
        A2.a.t(arrayList, "👩\u200d🦲", "🧑\u200d🦲", "👱\u200d♂️", "👱\u200d♀️");
        A2.a.t(arrayList, "👴", "👵", "🧓", "🙍\u200d♂️");
        A2.a.t(arrayList, "🙍\u200d♀️", "🙍", "🙎\u200d♂️", "🙎\u200d♀️");
        A2.a.t(arrayList, "🙎", "🙅\u200d♂️", "🙅\u200d♀️", "🙅");
        A2.a.t(arrayList, "🙆\u200d♂️", "🙆\u200d♀️", "🙆", "💁\u200d♂️");
        A2.a.t(arrayList, "💁\u200d♀️", "💁", "🙋\u200d♂️", "🙋\u200d♀️");
        A2.a.t(arrayList, "🙋", "🧏\u200d♂️", "🧏\u200d♀️", "🧏");
        A2.a.t(arrayList, "🙇\u200d♂️", "🙇\u200d♀️", "🙇", "🤦\u200d♂️");
        A2.a.t(arrayList, "🤦\u200d♀️", "🤦", "🤷\u200d♂️", "🤷\u200d♀️");
        A2.a.t(arrayList, "🤷", "👨\u200d⚕️", "👩\u200d⚕️", "🧑\u200d⚕️");
        A2.a.t(arrayList, "👨\u200d🎓", "👩\u200d🎓", "🧑\u200d🎓", "👨\u200d🏫");
        A2.a.t(arrayList, "👩\u200d🏫", "🧑\u200d🏫", "👨\u200d⚖️", "👩\u200d⚖️");
        A2.a.t(arrayList, "🧑\u200d⚖️", "👨\u200d🌾", "👩\u200d🌾", "🧑\u200d🌾");
        A2.a.t(arrayList, "👨\u200d🍳", "👩\u200d🍳", "🧑\u200d🍳", "👨\u200d🔧");
        A2.a.t(arrayList, "👩\u200d🔧", "🧑\u200d🔧", "👨\u200d🏭", "👩\u200d🏭");
        A2.a.t(arrayList, "🧑\u200d🏭", "👨\u200d💼", "👩\u200d💼", "🧑\u200d💼");
        A2.a.t(arrayList, "👨\u200d🔬", "👩\u200d🔬", "🧑\u200d🔬", "👨\u200d💻");
        A2.a.t(arrayList, "👩\u200d💻", "🧑\u200d💻", "👨\u200d🎤", "👩\u200d🎤");
        A2.a.t(arrayList, "🧑\u200d🎤", "👨\u200d🎨", "👩\u200d🎨", "🧑\u200d🎨");
        A2.a.t(arrayList, "👨\u200d✈️", "👩\u200d✈️", "🧑\u200d✈️", "👨\u200d🚀");
        A2.a.t(arrayList, "👩\u200d🚀", "🧑\u200d🚀", "👨\u200d🚒", "👩\u200d🚒");
        A2.a.t(arrayList, "🧑\u200d🚒", "👮\u200d♂️", "👮\u200d♀️", "👮");
        A2.a.t(arrayList, "🕵️\u200d♂️", "🕵️\u200d♀️", "🕵", "💂\u200d♂️");
        A2.a.t(arrayList, "💂\u200d♀️", "💂", "🥷", "👷\u200d♂️");
        A2.a.t(arrayList, "👷\u200d♀️", "👷", "🫅", "🤴");
        A2.a.t(arrayList, "👸", "👳\u200d♂️", "👳\u200d♀️", "👳");
        A2.a.t(arrayList, "👲", "🧕", "🤵\u200d♂️", "🤵\u200d♀️");
        A2.a.t(arrayList, "🤵", "👰\u200d♂️", "👰\u200d♀️", "👰");
        A2.a.t(arrayList, "🤰", "🫃", "🫄", "🤱");
        A2.a.t(arrayList, "👨\u200d🍼", "👩\u200d🍼", "🧑\u200d🍼", "👼");
        A2.a.t(arrayList, "🎅", "🤶", "🧑\u200d🎄", "🦸\u200d♂️");
        A2.a.t(arrayList, "🦸\u200d♀️", "🦸", "🦹\u200d♂️", "🦹\u200d♀️");
        A2.a.t(arrayList, "🦹", "🧙\u200d♂️", "🧙\u200d♀️", "🧙");
        A2.a.t(arrayList, "🧚\u200d♂️", "🧚\u200d♀️", "🧚", "🧛\u200d♂️");
        A2.a.t(arrayList, "🧛\u200d♀️", "🧛", "🧜\u200d♂️", "🧜\u200d♀️");
        A2.a.t(arrayList, "🧜", "🧝\u200d♂️", "🧝\u200d♀️", "🧝");
        A2.a.t(arrayList, "🧞\u200d♂️", "🧞\u200d♀️", "🧞", "🧟\u200d♂️");
        A2.a.t(arrayList, "🧟\u200d♀️", "🧟", "🧌", "💆\u200d♂️");
        A2.a.t(arrayList, "💆\u200d♀️", "💆", "💇\u200d♂️", "💇\u200d♀️");
        A2.a.t(arrayList, "💇", "🚶\u200d♂️", "🚶\u200d♀️", "🚶");
        A2.a.t(arrayList, "🧍\u200d♂️", "🧍\u200d♀️", "🧍", "🧎\u200d♂️");
        A2.a.t(arrayList, "🧎\u200d♀️", "🧎", "👨\u200d🦯", "👩\u200d🦯");
        A2.a.t(arrayList, "🧑\u200d🦯", "👨\u200d🦼", "👩\u200d🦼", "🧑\u200d🦼");
        A2.a.t(arrayList, "👨\u200d🦽", "👩\u200d🦽", "🧑\u200d🦽", "🏃\u200d♂️");
        A2.a.t(arrayList, "🏃\u200d♀️", "🏃", "🕺", "💃");
        A2.a.t(arrayList, "🕴", "👯\u200d♂️", "👯\u200d♀️", "👯");
        A2.a.t(arrayList, "🧖\u200d♂️", "🧖\u200d♀️", "🧖", "🧗\u200d♂️");
        A2.a.t(arrayList, "🧗\u200d♀️", "🧗", "🤺", "🏇");
        A2.a.t(arrayList, "⛷️", "🏂", "🏌️\u200d♂️", "🏌️\u200d♀️");
        A2.a.t(arrayList, "🏌", "🏄\u200d♂️", "🏄\u200d♀️", "🏄");
        A2.a.t(arrayList, "🚣\u200d♂️", "🚣\u200d♀️", "🚣", "🏊\u200d♂️");
        A2.a.t(arrayList, "🏊\u200d♀️", "🏊", "⛹️\u200d♂️", "⛹️\u200d♀️");
        A2.a.t(arrayList, "⛹️", "🏋️\u200d♂️", "🏋️\u200d♀️", "🏋");
        A2.a.t(arrayList, "🚴\u200d♂️", "🚴\u200d♀️", "🚴", "🚵\u200d♂️");
        A2.a.t(arrayList, "🚵\u200d♀️", "🚵", "🤸\u200d♂️", "🤸\u200d♀️");
        A2.a.t(arrayList, "🤸", "🤼\u200d♂️", "🤼\u200d♀️", "🤼");
        A2.a.t(arrayList, "🤽\u200d♂️", "🤽\u200d♀️", "🤽", "🤾\u200d♂️");
        A2.a.t(arrayList, "🤾\u200d♀️", "🤾", "🤹\u200d♂️", "🤹\u200d♀️");
        A2.a.t(arrayList, "🤹", "🧘\u200d♂️", "🧘\u200d♀️", "🧘");
        A2.a.t(arrayList, "🛀", "🛌", "👬", "👫");
        A2.a.t(arrayList, "👭", "🧑\u200d🤝\u200d🧑", "👨\u200d❤️\u200d💋\u200d👨", "👩\u200d❤️\u200d💋\u200d👨");
        A2.a.t(arrayList, "👩\u200d❤️\u200d💋\u200d👩", "💏", "👨\u200d❤️\u200d👨", "👩\u200d❤️\u200d👨");
        A2.a.t(arrayList, "👩\u200d❤️\u200d👩", "💑", "👨\u200d👩\u200d👦", "👨\u200d👩\u200d👧");
        A2.a.t(arrayList, "👨\u200d👩\u200d👧\u200d👦", "👨\u200d👩\u200d👦\u200d👦", "👨\u200d👩\u200d👧\u200d👧", "👨\u200d👦");
        A2.a.t(arrayList, "👩\u200d👦", "🗣", "👤", "👥️");
        arrayList.add("🫂");
        arrayList.add("👣");
    }
}
